"""add_attendee_id_and_embedding_to_fact

Revision ID: 4286db5951f6
Revises: b81c35b669e2
Create Date: 2025-11-02 06:46:32.353027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4286db5951f6'
down_revision: Union[str, Sequence[str], None] = 'b81c35b669e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'embedding')
    # ### end Alembic commands ###
