"""add rsvp and going fields to event_attendee

Revision ID: 8236a9feef9e
Revises: 4286db5951f6
Create Date: 2025-11-02 07:34:35.356517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8236a9feef9e'
down_revision: Union[str, Sequence[str], None] = '4286db5951f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add columns as nullable
    op.add_column('event_attendee', sa.Column('rsvp', sa.Boolean(), nullable=True))
    op.add_column('event_attendee', sa.Column('going', sa.Boolean(), nullable=True))
    
    # Step 2: Set default values for existing rows
    op.execute("UPDATE event_attendee SET rsvp = false WHERE rsvp IS NULL")
    op.execute("UPDATE event_attendee SET going = false WHERE going IS NULL")
    
    # Step 3: Make columns non-nullable
    op.alter_column('event_attendee', 'rsvp', nullable=False)
    op.alter_column('event_attendee', 'going', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_attendee', 'going')
    op.drop_column('event_attendee', 'rsvp')
    # ### end Alembic commands ###
