"""add rsvp and going fields to event_attendee

Revision ID: 8236a9feef9e
Revises: 4286db5951f6
Create Date: 2025-11-02 07:34:35.356517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8236a9feef9e'
down_revision: Union[str, Sequence[str], None] = '4286db5951f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attendee', sa.Column('rsvp', sa.Boolean(), nullable=False))
    op.add_column('event_attendee', sa.Column('going', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_attendee', 'going')
    op.drop_column('event_attendee', 'rsvp')
    # ### end Alembic commands ###
