"""add_event_id_to_opinion

Revision ID: 9065788b4a4c
Revises: 8236a9feef9e
Create Date: 2025-11-02 10:55:33.047158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9065788b4a4c'
down_revision: Union[str, Sequence[str], None] = '8236a9feef9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop all existing opinions first (they don't have event_id)
    op.execute('DELETE FROM joined_opinion')
    op.execute('DELETE FROM opinion')

    # Now add the event_id column
    op.add_column('opinion', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'opinion', 'event', ['event_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opinion', type_='foreignkey')
    op.drop_column('opinion', 'event_id')
    # ### end Alembic commands ###
