"""replace hello with event models

Revision ID: b81c35b669e2
Revises: dc1cf3323bd8
Create Date: 2025-11-02 01:45:44.229842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81c35b669e2'
down_revision: Union[str, Sequence[str], None] = 'dc1cf3323bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_tables', sa.Integer(), nullable=False),
    sa.Column('ppl_per_table', sa.Integer(), nullable=False),
    sa.Column('chaos_temp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_table('opinion',
    sa.Column('opinion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opinion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('opinion_id')
    )
    op.create_index(op.f('ix_opinion_opinion_id'), 'opinion', ['opinion_id'], unique=False)
    op.create_table('event_attendee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('seat_no', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_attendee_id'), 'event_attendee', ['id'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fact', sa.String(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['event_attendee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_id'), 'fact', ['id'], unique=False)
    op.create_table('joined_opinion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('opinion_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['event_attendee.id'], ),
    sa.ForeignKeyConstraint(['opinion_id'], ['opinion.opinion_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joined_opinion_id'), 'joined_opinion', ['id'], unique=False)
    op.drop_index(op.f('ix_hello_id'), table_name='hello')
    op.drop_table('hello')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hello_pkey'))
    )
    op.create_index(op.f('ix_hello_id'), 'hello', ['id'], unique=False)
    op.drop_index(op.f('ix_joined_opinion_id'), table_name='joined_opinion')
    op.drop_table('joined_opinion')
    op.drop_index(op.f('ix_fact_id'), table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_event_attendee_id'), table_name='event_attendee')
    op.drop_table('event_attendee')
    op.drop_index(op.f('ix_opinion_opinion_id'), table_name='opinion')
    op.drop_table('opinion')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
